
import { EvaluationCriterion, QuestionType, ProposalCategory } from './types';

export const PROPOSAL_CATEGORIES: ProposalCategory[] = [
  ProposalCategory.PORTAL_BLOG,
  ProposalCategory.PORTAL_SOCIAL,
  ProposalCategory.TV_ALL,
  ProposalCategory.YOUTUBE_ALL,
];


export const EVALUATION_MATRIX: EvaluationCriterion[] = [
  // --- YOUTUBE SPECIFIC CRITERIA ---
  {
    id: 'youtube_video_quantity',
    criterion: 'Quantidade de vídeos',
    indicator: 'Volume de entregas contratadas',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Quantidade de vídeos a serem produzidos/veiculados',
    unit: 'number',
    options: [
      { label: '1 vídeo', value: { max: 1 }, score: 1 },
      { label: '2 vídeos', value: { min: 2, max: 2 }, score: 2 },
      { label: '3+ vídeos', value: { min: 3 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'youtube_views',
    criterion: 'Visualizações estimadas (YouTube)',
    indicator: 'Volume total de views garantidos',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Estimativa de visualizações totais',
    unit: 'number',
    options: [
      { label: '< 5 mil', value: { max: 5000 }, score: 0 },
      { label: '5-20 mil', value: { min: 5001, max: 20000 }, score: 1 },
      { label: '20-100 mil', value: { min: 20001, max: 100000 }, score: 2 },
      { label: '> 100 mil', value: { min: 100001 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'youtube_avg_duration',
    criterion: 'Duração média de visualização',
    indicator: 'Retenção da audiência (segundos)',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Duração média das visualizações (segundos)',
    unit: 'number',
    options: [
      { label: '< 30s', value: { max: 30 }, score: 0 },
      { label: '30s - 1min', value: { min: 31, max: 60 }, score: 1 },
      { label: '1min - 3min', value: { min: 61, max: 180 }, score: 2 },
      { label: '> 3min', value: { min: 181 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'youtube_history',
    criterion: 'Histórico de campanhas',
    indicator: 'Comprovação de performance anterior',
    questionType: QuestionType.SELECT,
    questionLabel: 'Apresentou histórico de campanhas anteriores com métricas?',
    options: [
      { label: 'Não apresentou', value: 'nao', score: 0 },
      { label: 'Sim, sem métricas detalhadas', value: 'sim_simples', score: 1 },
      { label: 'Sim, com métricas comprovadas', value: 'sim_completo', score: 3 },
    ],
    applicableCategories: [ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'youtube_demographic_rs',
    criterion: 'Audiência no RS (YouTube)',
    indicator: '% da audiência no RS (últimos 90 dias)',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Audiência no RS (%) nos últimos 90 dias',
    unit: 'percentage',
    options: [
      { label: '<25%', value: { max: 24.99 }, score: 0 },
      { label: '26-49%', value: { min: 25, max: 49 }, score: 1 },
      { label: '50-74%', value: { min: 49.01, max: 74 }, score: 2 },
      { label: '>75%', value: { min: 74.01 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'youtube_brand_usage',
    criterion: 'Aproveitamento de marca',
    indicator: 'Profundidade da integração da marca',
    questionType: QuestionType.SELECT,
    questionLabel: 'Qual o formato de aproveitamento da marca?',
    options: [
      { label: 'Apenas spot/inserção padrão', value: 'spot', score: 1 },
      { label: 'Citação (abertura/encerramento)', value: 'citacao', score: 2 },
      { label: 'Vídeo próprio / merchandising dedicado', value: 'dedicado', score: 3 },
    ],
    applicableCategories: [ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'youtube_content_rights',
    criterion: 'Licenciamento de conteúdo',
    indicator: 'Direito de uso em canais governamentais',
    questionType: QuestionType.SELECT,
    questionLabel: 'Liberação de uso do conteúdo em canais do Governo?',
    options: [
      { label: 'Não, uso restrito ao canal', value: 'nao', score: 0 },
      { label: 'Parcial (cross-posting)', value: 'parcial', score: 2 },
      { label: 'Sim, uso livre e irrestrito', value: 'sim', score: 3 },
    ],
    applicableCategories: [ProposalCategory.YOUTUBE_ALL],
  },


  // --- TV SPECIFIC CRITERIA ---
  {
    id: 'tv_program_type',
    criterion: 'Determinação de programação',
    indicator: 'Exposição em programa específico vs rotativo',
    questionType: QuestionType.SELECT,
    questionLabel: 'A mídia é determinada em programa específico?',
    options: [
      { label: 'Rotativo (indeterminado)', value: 'rotativo', score: 1 },
      { label: 'Faixa horária fixa', value: 'faixa', score: 2 },
      { label: 'Programa específico (determinado)', value: 'determinado', score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL],
  },
  {
    id: 'tv_daily_insertions',
    criterion: 'Volume diário',
    indicator: 'Número de inserções por dia',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Número de inserções diárias',
    unit: 'number',
    options: [
      { label: '1 inserção', value: { max: 1 }, score: 0 },
      { label: '2-3 inserções', value: { min: 2, max: 3 }, score: 1 },
      { label: '4-5 inserções', value: { min: 4, max: 5 }, score: 2 },
      { label: '6+ inserções', value: { min: 6 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL],
  },
  {
    id: 'tv_insertion_days',
    criterion: 'Duração da campanha (dias)',
    indicator: 'Dias com veiculação ativa',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Quantos dias a proposta contempla?',
    unit: 'number',
    options: [
      { label: 'Curto prazo (<7 dias)', value: { max: 6 }, score: 1 },
      { label: 'Médio prazo (7-14 dias)', value: { min: 7, max: 14 }, score: 2 },
      { label: 'Longo prazo (>15 dias)', value: { min: 15 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL],
  },
  {
    id: 'tv_spot_duration',
    criterion: 'Formato da inserção',
    indicator: 'Tempo da peça publicitária',
    questionType: QuestionType.SELECT,
    questionLabel: 'Formato/duração da inserção',
    options: [
      { label: '15 segundos', value: 15, score: 1 },
      { label: '30 segundos', value: 30, score: 2 },
      { label: '60 segundos', value: 60, score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL],
  },
  {
    id: 'tv_daypart',
    criterion: 'Turno de exposição',
    indicator: 'Faixa horária predominante',
    questionType: QuestionType.SELECT,
    questionLabel: 'Qual o turno de exposição predominante?',
    options: [
      { label: 'Rotativo', value: 'rotativo', score: 1 },
      { label: 'Matutino', value: 'matutino', score: 2 },
      { label: 'Vespertino', value: 'vespertino', score: 2 },
      { label: 'Noturno', value: 'noturno', score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL],
  },
  {
    id: 'tv_audience_source',
    criterion: 'Fonte de audiência (TV)',
    indicator: 'Origem dos dados de medição',
    questionType: QuestionType.SELECT,
    questionLabel: 'Como a audiência é medida?',
    options: [
      { label: 'Sem dados / estimativa interna', value: 'estimado', score: 0 },
      { label: 'Dados históricos da emissora', value: 'historico', score: 1 },
      { label: 'Kantar IBOPE / TechEdge (auditado)', value: 'auditado', score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL],
  },
  {
    id: 'demographic_rs_tv',
    criterion: 'Audiência no RS (TV)',
    indicator: '% da audiência total no RS',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Audiência no RS (%) em (nos últimos 90 dias) - TV',
    unit: 'percentage',
    options: [
      { label: '<25%', value: { max: 24.99 }, score: 0 },
      { label: '26-49%', value: { min: 25, max: 49 }, score: 1 },
      { label: '50-74%', value: { min: 49.01, max: 74 }, score: 2 },
      { label: '>75%', value: { min: 74.01 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL],
  },
  {
    id: 'tv_simultaneous_transmission',
    criterion: 'Transmissão simultânea',
    indicator: 'Entrega multiplataforma (TV + digital)',
    questionType: QuestionType.SELECT,
    questionLabel: 'Inclui transmissão simultânea em Youtube ou CTV?',
    options: [
      { label: 'Não, apenas TV linear', value: 'nao', score: 0 },
      { label: 'Sim, no YouTube da emissora', value: 'youtube', score: 2 },
      { label: 'Sim, via CTV/streaming próprio', value: 'ctv', score: 3 },
      { label: 'Sim, YouTube + CTV (combo)', value: 'combo', score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL],
  },
  
  // --- EXISTING CRITERIA ---
  {
    id: 'portal_existence',
    criterion: 'Existência de portal próprio, com atualização de conteúdo',
    indicator: 'Domínio ativo e atualizado',
    questionType: QuestionType.SELECT,
    questionLabel: 'Qual o status de atualização do portal?',
    options: [
      { label: 'Inexistente', value: 'inexistente', score: 0 },
      { label: 'Existe mas desatualizado', value: 'desatualizado', score: 1 },
      { label: 'Atualizado semanalmente', value: 'semanal', score: 2 },
      { label: 'Atualizado diariamente', value: 'diario', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'portal_audience',
    criterion: 'Audiência no portal',
    indicator: 'Pageviews (média dos últimos 90 dias)',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Pageviews (média dos últimos 90 dias)',
    unit: 'number',
    options: [
      { label: '<15 mil', value: { max: 15000 }, score: 0 },
      { label: '16-100 mil', value: { min: 15001, max: 100000 }, score: 1 },
      { label: '101-299 mil', value: { min: 100001, max: 299000 }, score: 2 },
      { label: '>300 mil', value: { min: 299001 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'social_followers',
    criterion: 'Seguidores em redes sociais',
    indicator: 'Total consolidado e canais ativos',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Seguidores/assinantes (#)',
    unit: 'number',
    options: [
      { label: '<10 mil', value: { max: 10000 }, score: 0 },
      { label: '11-50mil', value: { min: 10001, max: 50000 }, score: 1 },
      { label: '50-99 mil', value: { min: 50001, max: 99000 }, score: 2 },
      { label: '>100 mil', value: { min: 99001 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'avg_reach',
    criterion: 'Alcance médio por publicação',
    indicator: '% dos seguidores',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Alcance médio por publicação (% dos seguidores)',
    info: 'Insira apenas o número. Ex: para 10%, digite 10.',
    unit: 'percentage',
    options: [
      { label: '<3%', value: { max: 2.99 }, score: 0 },
      { label: '3-8%', value: { min: 3, max: 8 }, score: 1 },
      { label: '8-15%', value: { min: 8.01, max: 15 }, score: 2 },
      { label: '>15%', value: { min: 15.01 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'video_views',
    criterion: 'Visualizações de vídeo',
    indicator: 'Média dos últimos 90 dias',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Média de visualizações de vídeo (90 dias)',
    unit: 'number',
    options: [
      { label: '<2 mil', value: { max: 2000 }, score: 0 },
      { label: '2-10 mil', value: { min: 2001, max: 10000 }, score: 1 },
      { label: '10-40 mil', value: { min: 10001, max: 40000 }, score: 2 },
      { label: '>40 mil', value: { min: 40001 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'complementary_formats',
    criterion: 'Formatos complementares',
    indicator: 'Newsletter, podcast, vídeo',
    questionType: QuestionType.SELECT,
    questionLabel: 'Quantos formatos complementares são oferecidos?',
    options: [
      { label: 'Nenhum', value: '0', score: 0 },
      { label: '1 formato', value: '1', score: 1 },
      { label: '2 formatos', value: '2', score: 2 },
      { label: '3+ formatos', value: '3', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'crossposting',
    criterion: 'Crossposting',
    indicator: 'Qtd. de canais integrados na proposta comercial',
    questionType: QuestionType.SELECT,
    questionLabel: 'Qtd. de canais integrados na proposta?',
    options: [
      { label: 'Nenhum', value: '0', score: 0 },
      { label: '1 canal', value: '1', score: 0 }, 
      { label: '2 canais', value: '2', score: 1 },
      { label: '3 canais', value: '3', score: 2 },
      { label: '4+ canais', value: '4', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'branded_content',
    criterion: 'Branded content / merchandising',
    indicator: 'Inclusão de conteúdo de marca/product placement',
    questionType: QuestionType.SELECT,
    questionLabel: 'A proposta inclui branded content / merchandising?',
    options: [
      { label: 'Não', value: 'nao', score: 0 },
      { label: 'Sim', value: 'sim', score: 3 },
    ],
    applicableCategories: [ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'branded_content_text',
    criterion: 'Branded content (texto)',
    indicator: 'Inclusão de conteúdo de marca em texto',
    questionType: QuestionType.SELECT,
    questionLabel: 'A proposta inclui branded content em texto?',
    options: [
      { label: 'Não', value: 'nao', score: 0 },
      { label: 'Sim', value: 'sim', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL],
  },
  {
    id: 'demographic_rs_portal',
    criterion: 'Audiência no RS (portal)',
    indicator: '% da audiência total do portal no RS',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Audiência no RS (%) em (nos últimos 90 dias) - portal',
    unit: 'percentage',
    options: [
      { label: '<25%', value: { max: 24.99 }, score: 0 },
      { label: '26-49%', value: { min: 25, max: 49 }, score: 1 },
      { label: '50-74%', value: { min: 49.01, max: 74 }, score: 2 },
      { label: '>75%', value: { min: 74.01 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'demographic_rs_social',
    criterion: 'Audiência no RS (redes sociais)',
    indicator: '% da audiência total das redes no RS',
    questionType: QuestionType.NUMBER,
    questionLabel: 'Audiência no RS (%) em (nos últimos 30 dias) - redes sociais',
    info: 'Insira o percentual de audiência das redes sociais localizada no RS.',
    unit: 'percentage',
    options: [
        { label: '<25%', value: { max: 24.99 }, score: 0 },
        { label: '26-49%', value: { min: 25, max: 49 }, score: 1 },
        { label: '50-74%', value: { min: 49.01, max: 74 }, score: 2 },
        { label: '>75%', value: { min: 74.01 }, score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'privileged_visibility',
    criterion: 'Visibilidade privilegiada',
    indicator: 'Home/topo/destaque',
    questionType: QuestionType.SELECT,
    questionLabel: 'Nível de visibilidade dos banners no portal',
    options: [
      { label: 'Nenhum', value: 'nenhum', score: 0 },
      { label: 'Visibilidade média', value: 'media', score: 1 },
      { label: 'Boa visibilidade', value: 'boa', score: 2 },
      { label: 'Destaque premium', value: 'premium', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'cpm',
    criterion: 'CPM',
    indicator: 'Custo por mil - valor bruto',
    questionType: QuestionType.NUMBER,
    questionLabel: 'CPM (Custo por mil) - valor bruto (R$)',
    unit: 'currency',
    options: [
      { label: '< R$ 20', value: { max: 19.99 }, score: 3 },
      { label: 'R$ 20-40', value: { min: 20, max: 40 }, score: 2 },
      { label: 'R$ 40-60', value: { min: 40.01, max: 60 }, score: 1 },
      { label: '> R$ 60', value: { min: 60.01 }, score: 0 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'cpc',
    criterion: 'CPC',
    indicator: 'Custo por clique - valor bruto',
    questionType: QuestionType.NUMBER,
    questionLabel: 'CPC (Custo por clique) - valor bruto (R$)',
    unit: 'currency',
    options: [
      { label: '< R$ 1', value: { max: 0.99 }, score: 3 },
      { label: 'R$ 1-2', value: { min: 1, max: 2 }, score: 2 },
      { label: 'R$ 2-3', value: { min: 2.01, max: 3 }, score: 1 },
      { label: '> R$ 3', value: { min: 3.01 }, score: 0 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'real_reach_portal',
    criterion: 'Fonte de dados de alcance (portal)',
    indicator: 'Comprovação da origem dos dados de alcance do portal',
    questionType: QuestionType.SELECT,
    questionLabel: 'Fonte de dados de alcance do portal',
    options: [
      { label: 'Não estimado', value: 'nao_estimado', score: 0 },
      { label: 'Genérico/informado pelo veículo', value: 'generico', score: 1 },
      { label: 'Baseado em Google Analytics', value: 'historico', score: 2 },
      { label: 'Auditado por terceiro', value: 'auditado', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
    {
    id: 'real_reach_social',
    criterion: 'Fonte de dados de alcance (social)',
    indicator: 'Comprovação da origem dos dados de alcance social',
    questionType: QuestionType.SELECT,
    questionLabel: 'Fonte de dados de alcance das redes sociais',
    options: [
      { label: 'Não estimado', value: 'nao_estimado', score: 0 },
      { label: 'Genérico/informado pelo veículo', value: 'generico', score: 1 },
      { label: 'Nativo (Meta, YT Studio, etc)', value: 'historico', score: 2 },
      { label: 'Auditado por terceiro', value: 'auditado', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'portal_formats',
    criterion: 'Formatos obrigatórios de portal',
    indicator: '300x250, 320x100, 728x90',
    questionType: QuestionType.SELECT,
    questionLabel: 'Quantos formatos obrigatórios de portal estão inclusos?',
    options: [
      { label: 'Nenhum', value: '0', score: 0 },
      { label: '1 formato', value: '1', score: 1 },
      { label: '2 formatos', value: '2', score: 2 },
      { label: '3 formatos', value: '3', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'social_formats',
    criterion: 'Formatos obrigatórios de redes sociais',
    indicator: 'Reels, feed, stories, artigo, áudio, carrosel, insert de marca, vinheta de 5"',
    questionType: QuestionType.SELECT,
    questionLabel: 'Quantos formatos obrigatórios de redes sociais estão inclusos?',
    options: [
      { label: 'Nenhum', value: '0', score: 0 },
      { label: '1 formato', value: '1', score: 1 },
      { label: '2 formatos', value: '2', score: 2 },
      { label: '3 formatos', value: '3', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'bonus_portal',
    criterion: 'Bonificação em mídia (portal)',
    indicator: 'Volume extra concedido sem custo (Impressões/Diárias)',
    questionType: QuestionType.SELECT,
    questionLabel: 'Avalie a relevância da bonificação no portal',
    options: [
      { label: 'Nenhuma bonificação', value: 'nenhuma', score: 0 },
      { label: 'Baixa relevância (ex: banners residuais)', value: 'baixa', score: 1 },
      { label: 'Média relevância (ex: +10-20% volume)', value: 'media', score: 2 },
      { label: 'Alta relevância (ex: >20% ou formatos premium)', value: 'alta', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_BLOG, ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
  {
    id: 'bonus_social',
    criterion: 'Bonificação em mídia (social)',
    indicator: 'Entregas extras concedidas (Posts/Stories/Impulsionamento)',
    questionType: QuestionType.SELECT,
    questionLabel: 'Avalie a relevância da bonificação social',
    options: [
      { label: 'Nenhuma bonificação', value: 'nenhuma', score: 0 },
      { label: 'Baixa relevância', value: 'baixa', score: 1 },
      { label: 'Média relevância', value: 'media', score: 2 },
      { label: 'Alta relevância', value: 'alta', score: 3 },
    ],
    applicableCategories: [ProposalCategory.PORTAL_SOCIAL, ProposalCategory.TV_ALL, ProposalCategory.YOUTUBE_ALL],
  },
];

export const CRITERIA_BLOCKS = [
    {
      name: 'Métricas do canal YouTube',
      ids: ['youtube_views', 'youtube_avg_duration', 'youtube_history', 'youtube_demographic_rs', 'youtube_video_quantity', 'youtube_brand_usage', 'youtube_content_rights']
    },
    {
      name: 'Métricas de televisão',
      descriptionId: 'tv_audience_details',
      descriptionLabel: 'Detalhes sobre o perfil da audiência',
      ids: ['tv_daily_insertions', 'tv_insertion_days', 'tv_spot_duration', 'tv_daypart', 'tv_program_type', 'tv_audience_source', 'demographic_rs_tv', 'tv_simultaneous_transmission']
    },
    {
      name: 'Portal/Blog',
      descriptionId: 'portal_blog_description',
      descriptionLabel: 'Descrição do aproveitamento em portal/blog',
      ids: ['portal_existence', 'portal_audience', 'demographic_rs_portal', 'real_reach_portal', 'portal_formats', 'privileged_visibility', 'branded_content_text', 'bonus_portal']
    },
    {
      name: 'Redes sociais',
      descriptionId: 'social_media_description',
      descriptionLabel: 'Descrição do aproveitamento em redes sociais',
      ids: ['social_followers', 'avg_reach', 'video_views', 'demographic_rs_social', 'real_reach_social', 'social_formats', 'bonus_social']
    },
    {
      name: 'Métricas comerciais',
      ids: ['cpm', 'cpc']
    },
    {
      name: 'Outros aproveitamentos',
      ids: ['complementary_formats', 'crossposting', 'branded_content']
    }
];